defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 123456
  host: localhost
  min_messages: WARNING

development:
  <<: *defaults
  database: matricula_development

test:
  <<: *defaults
  database: matricula_test

production:
  <<: *defaults
  database: matricula_production